### ISSUE TITLE
Unit tests for project creation

### ISSUE THREAD

**Issue by philippepons** [chartes/dots#33]
**Objectives:** to be able to launch unit test modules from an XQuery script.

This script should be able to :
1. create a test environment (including downloading data, creating the db according to DoTS requirements, etc.);
2. run the tests of one or more unit test modules (with a function such as `script:execute()` ?), as chosen by the user;
3. clean up the test environment (delete the *project* db, update the DoTS switcher, etc.), if needeed.

The `tests/project_create/dots_test_setup.xqm` file contains all the functions required for points 1. and 3.
The files `tests/project_create/db_create_test.xq`, `tests/project_create/project_registers_create_test.xq`, `tests/project_create/TEI_add_id_test.xq`, and `tests/project_create/dots_switcher_update_test.xq` are the unit test modules for point 2.
At present, all these unit test modules work, but each module requires the test environment to be created, which can take some times if you want to run all the tests in the `tests/project_create` folder.

**Comment by ChristianGruen** [comment]
One way to run tests with `proc:system`:

```xquery
let $result := proc:system(
  'java',
  ('-cp', 'path/to/basex.jar', 'org.basex.BaseX', '-t', 'tests-dir/')
)
let $xml := parse-xml($result)
return $xml//testcase
```

Another cleaner way could be to add a `unit:execute` function that allows to run tests from a XQuery script (could be appr. 2 days to implement and document it).

**Comment by philippepons** [comment]
After some thought, I’ve decided to change my approach.

Some time ago, I wrote a bash script to create a DoTS project. As a first step, I’ve extended this script so that it can now run unit tests immediately after creating the project.
I’ve updated the unit tests accordingly ([see tests/project_create](https://github.com/chartes/dots/tree/unit-test/tests/project_create)) as well as the bash script itself ([scripts/project_create.sh](https://github.com/chartes/dots/blob/unit-test/scripts/project_create.sh)).

That said, a more robust solution would be to run the XQuery unit tests automatically via GitHub Actions, e.g. on each PR.
Would that be feasible? Would you be open to testing this setup together?

**Comment by ChristianGruen** [comment]
> That said, a more robust solution would be to run the XQuery unit tests automatically via GitHub Actions, e.g. on each PR. Would that be feasible? Would you be open to testing this setup together?

Certainly! Here is a stub that we could adapt and extend:

```yml
# xqunit.yml
name: XQUnit Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install BaseX
      run: |
        wget https://files.basex.org/releases/11.9/BaseX119.zip
        unzip BaseX119.zip
    - name: Run tests
      run: |
        ./basex/bin/basex -W -o xqunit.xml -t test/
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: xqunit
        path: xqunit.xml
```
